python-targets: 3.5

test-warnings: no
max-line-length: 79
uses:
    - django
autodetect: yes
requirements:
    - requirements.txt
pylint:
    disable:
        - old-style-class
        - missing-super-argument
        
