language: python

python:
  - "3.4"

install:
 - pip install coveralls
 - pip install -r requirements.txt

script:
 - coverage run --source=Seeder Seeder/manage.py test --settings=settings.tests
after_script:
  coveralls