web:
  build: Dockerfile
  restart: always
  build: .
  ports:
   - "8000:8000"
  links:
    - postgres
    - mysql
    - elastic
    - memcached
    - manet
  volumes:
   - .:/code
  command: fab run_local
  working_dir: /code/Seeder

postgres:
  restart: always
  image: postgres:latest
  ports:
    - "5432:5432"
  volumes_from:
    - data

data:
  image: busybox
  volumes:
    - "/var/lib/postgresql"

mysql:
  image: mysql:latest
  expose:
   - '3306'
  volumes:
   - ./legacy_dumps:/docker-entrypoint-initdb.d/
  environment:
   - MYSQL_ROOT_PASSWORD=legacy
   - MYSQL_USER=legacy
   - MYSQL_PASSWORD=legacy
   - MYSQL_DATABASE=legacy_db

elastic:
  image: elasticsearch:latest

memcached:
  image: memcached:latest

manet:
  image: bobey/manet:latest