web:
  build: .
  ports:
   - "8000:8000"
  links:
    - postgres
    - mysql
    - elastic
    - memcached
    - manet
  volumes:
   - .:/code
  command: bash run.sh
  working_dir: /code/Seeder

postgres:
  image: postgres:latest
  ports:
    - "5432:5432"
  volumes_from:
    - data

data:
  image: busybox
  volumes:
    - "/var/lib/postgresql"

mysql:
  image: mysql:latest
  ports:
   - "3306:3306"
  volumes:
   - ./legacy_dumps:/docker-entrypoint-initdb.d/
  environment:
   - MYSQL_ROOT_PASSWORD=legacy
   - MYSQL_USER=legacy
   - MYSQL_PASSWORD=legacy
   - MYSQL_DATABASE=legacy_db

elastic:
  dockerfile: Dockerfile_elastic
  build: .

memcached:
  image: memcached:latest

manet:
  image: bobey/manet:latest

#myadmin:
#  image: phpmyadmin/phpmyadmin:latest
#  environment:
#    - MYSQL_ROOT_PASSWORD=legacy
#    - PMA_ARBITRARY=1
#    - PMA_HOST=mysql
#  ports:
#    - "8080:8080"
#    - "80:80"
#  links:
#    - mysql
