web:
  restart: always
  build: .
  ports:
   - "8000:8000"
  links:
    - postgres
    - mysql
  volumes:
   - .:/code
  command: fab run_local
  working_dir: /code/Seeder

postgres:
  restart: always
  image: postgres:latest
  volumes:
    - "~/postgres_data:/var/lib/postgresql"
  ports:
    - "5432:5432"

mysql:
  image: mysql:latest
  expose:
   - '3306'
  volumes:
   - ./legacy_dumps:/docker-entrypoint-initdb.d/
  environment:
   - MYSQL_ROOT_PASSWORD=mysql
