# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-25 16:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import search_blob.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityAssuranceCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_changed', models.DateTimeField(auto_now=True)),
                ('content_changed', models.BooleanField(default=False, verbose_name='Content changed too much')),
                ('technical_quality_changed', models.BooleanField(default=False, verbose_name='Technical side decreased too much')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('source_action', models.CharField(blank=True, choices=[('voting', 'Voting'), ('duplicity', 'Duplicated record'), ('waiting', 'Waiting for response'), ('reevaluation', 'Waiting for reevaluation'), ('technical', 'Technical review'), ('communication', 'In communication'), ('vote_accepted', 'Accepted by staff'), ('vote_declined', 'Declined by staff'), ('success', 'Archiving accepted'), ('forced', 'Archiving without publisher consent'), ('declined', 'Declined by publisher'), ('ignored', 'Publisher ignored requests'), ('expired', 'Contract expired'), ('terminated', 'Contract terminated')], help_text='This will close QA and act upon the source', max_length=15, null=True, verbose_name='Resulting action')),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Checked by')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='source.Source', verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Quality assurance check',
                'verbose_name_plural': 'Quality assurance checks',
            },
            bases=(search_blob.models.SearchModel, models.Model),
        ),
    ]
