# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 10:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_auto_20160419_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityassurancecheck',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='qualityassurancecheck',
            name='source_action',
            field=models.CharField(blank=True, choices=[('voting', 'Voting'), ('duplicity', 'Duplicated record'), ('waiting', 'Waiting for response'), ('reevaluation', 'Waiting for reevaluation'), ('technical', 'Technical review'), ('communication', 'In communication'), ('vote_accepted', 'Accepted by staff'), ('vote_declined', 'Declined by staff'), ('success', 'Archiving accepted'), ('forced', 'Archiving without publisher consent'), ('declined', 'Declined by publisher'), ('ignored', 'Publisher ignored requests'), ('expired', 'Contract expired'), ('terminated', 'Contract terminated')], help_text='This will close QA and act upon the source', max_length=15, null=True, verbose_name='Resulting action'),
        ),
    ]
