# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0005_auto_20160518_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualityassurancecheck',
            options={'verbose_name': 'Quality assurance check', 'verbose_name_plural': 'Quality assurance checks'},
        ),
    ]
