# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('source', '0022_auto_20160518_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_changed', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('annotation', models.TextField()),
                ('image', models.ImageField(upload_to='photos')),
                ('source_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='news_a', to='source.Source')),
                ('source_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='news_b', to='source.Source')),
            ],
            options={
                'abstract': False,
                'ordering': ('-last_changed',),
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=256)),
                ('log_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='TopicCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_changed', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('annotation', models.TextField()),
                ('image', models.ImageField(upload_to='photos')),
                ('sources', models.ManyToManyField(to='source.Source')),
            ],
            options={
                'abstract': False,
                'ordering': ('-last_changed',),
            },
        ),
    ]
