# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 23:51
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import www.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('source', '0023_auto_20170130_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_changed', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('title_cs', models.CharField(max_length=150, null=True)),
                ('title_en', models.CharField(max_length=150, null=True)),
                ('annotation', ckeditor.fields.RichTextField()),
                ('annotation_cs', ckeditor.fields.RichTextField(null=True)),
                ('annotation_en', ckeditor.fields.RichTextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('annotation_source_1', ckeditor.fields.RichTextField(blank=True, help_text='Leave empty to use source annotation', null=True)),
                ('annotation_source_1_cs', ckeditor.fields.RichTextField(blank=True, help_text='Leave empty to use source annotation', null=True)),
                ('annotation_source_1_en', ckeditor.fields.RichTextField(blank=True, help_text='Leave empty to use source annotation', null=True)),
                ('annotation_source_2', ckeditor.fields.RichTextField(blank=True, help_text='Leave empty to use source annotation', null=True)),
                ('annotation_source_2_cs', ckeditor.fields.RichTextField(blank=True, help_text='Leave empty to use source annotation', null=True)),
                ('annotation_source_2_en', ckeditor.fields.RichTextField(blank=True, help_text='Leave empty to use source annotation', null=True)),
                ('source_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='news_a', to='source.Source')),
                ('source_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='news_b', to='source.Source')),
            ],
            options={
                'verbose_name_plural': 'News articles',
                'verbose_name': 'News article',
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=256)),
                ('log_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='TopicCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_changed', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('title_cs', models.CharField(max_length=150, null=True)),
                ('title_en', models.CharField(max_length=150, null=True)),
                ('annotation', ckeditor.fields.RichTextField()),
                ('annotation_cs', ckeditor.fields.RichTextField(null=True)),
                ('annotation_en', ckeditor.fields.RichTextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('sources', models.ManyToManyField(to='source.Source')),
            ],
            options={
                'verbose_name_plural': 'Topic collections',
                'verbose_name': 'Topic collection',
            },
        ),
    ]
