# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsobject',
            options={'verbose_name': 'News article', 'verbose_name_plural': 'News articles'},
        ),
        migrations.AddField(
            model_name='newsobject',
            name='annotation_cs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsobject',
            name='annotation_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsobject',
            name='title_cs',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='newsobject',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='topiccollection',
            name='annotation_cs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topiccollection',
            name='annotation_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topiccollection',
            name='title_cs',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='topiccollection',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
