# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccollection',
            name='sources',
            field=models.ManyToManyField(blank=True, null=True, to='source.Source'),
        ),
    ]
