# Generated by Django 2.2.28 on 2023-11-10 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtinctWebsite',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_changed', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=128, verbose_name='UUID')),
                ('url', models.TextField(verbose_name='URL')),
                ('date_monitoring_start', models.DateTimeField(blank=True, null=True, verbose_name='Date started monitoring')),
                ('date_extinct', models.DateTimeField(blank=True, null=True, verbose_name='Date extinct')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='Status code')),
                ('status_dead', models.BooleanField(verbose_name='Dead')),
                ('status_confirmed', models.BooleanField(verbose_name='Confirmed dead')),
                ('status_requires', models.BooleanField(verbose_name='Requires confirmation')),
                ('status_metadata', models.BooleanField(verbose_name='Contains metadata')),
                ('status_metadata_match', models.IntegerField(verbose_name='Death index')),
                ('status_whois', models.BooleanField(verbose_name='Contains whois')),
                ('status_date', models.DateTimeField(verbose_name='Datum poslední kontroly')),
            ],
            options={
                'verbose_name': 'Extinct Website',
                'verbose_name_plural': 'Extinct Websites',
            },
        ),
    ]
