# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_auto_20170204_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccollection',
            name='sources',
            field=models.ManyToManyField(blank=True, to='source.Source'),
        ),
    ]
