# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 01:54
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_auto_20170130_0102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topiccollection',
            options={'verbose_name': 'Topic collection', 'verbose_name_plural': 'Topic collections'},
        ),
        migrations.AlterField(
            model_name='newsobject',
            name='annotation',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='newsobject',
            name='annotation_cs',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='newsobject',
            name='annotation_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='newsobject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='topiccollection',
            name='annotation',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='topiccollection',
            name='annotation_cs',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='topiccollection',
            name='annotation_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
