# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 20:52
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_auto_20170130_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsobject',
            name='annotation_source_1',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Leave empty to use source annotation', null=True),
        ),
        migrations.AddField(
            model_name='newsobject',
            name='annotation_source_2',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Leave empty to use source annotation', null=True),
        ),
    ]
