# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_auto_20170216_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topiccollection',
            options={'ordering': ['id'], 'verbose_name': 'Topic collection', 'verbose_name_plural': 'Topic collections'},
        ),
    ]
