# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 20:57
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_auto_20170130_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsobject',
            name='annotation_source_1_cs',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Leave empty to use source annotation', null=True),
        ),
        migrations.AddField(
            model_name='newsobject',
            name='annotation_source_1_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Leave empty to use source annotation', null=True),
        ),
        migrations.AddField(
            model_name='newsobject',
            name='annotation_source_2_cs',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Leave empty to use source annotation', null=True),
        ),
        migrations.AddField(
            model_name='newsobject',
            name='annotation_source_2_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Leave empty to use source annotation', null=True),
        ),
    ]
