# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_auto_20170223_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topiccollection',
            name='sources',
        ),
        migrations.DeleteModel(
            name='TopicCollection',
        ),
    ]
