# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-10 23:50
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0005_auto_20170226_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsobject',
            name='annotation_source_1',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Leave empty to use source annotation', null=True, verbose_name='annotation for first source'),
        ),
        migrations.AlterField(
            model_name='newsobject',
            name='annotation_source_1_cs',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Leave empty to use source annotation', null=True, verbose_name='annotation for first source'),
        ),
        migrations.AlterField(
            model_name='newsobject',
            name='annotation_source_1_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Leave empty to use source annotation', null=True, verbose_name='annotation for first source'),
        ),
        migrations.AlterField(
            model_name='newsobject',
            name='annotation_source_2',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Leave empty to use source annotation', null=True, verbose_name='annotation for second source'),
        ),
        migrations.AlterField(
            model_name='newsobject',
            name='annotation_source_2_cs',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Leave empty to use source annotation', null=True, verbose_name='annotation for second source'),
        ),
        migrations.AlterField(
            model_name='newsobject',
            name='annotation_source_2_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Leave empty to use source annotation', null=True, verbose_name='annotation for second source'),
        ),
        migrations.AlterField(
            model_name='newsobject',
            name='source_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='news_a', to='source.Source', verbose_name='First source'),
        ),
        migrations.AlterField(
            model_name='newsobject',
            name='source_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='news_b', to='source.Source', verbose_name='second source'),
        ),
    ]
