# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-20 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0006_auto_20170310_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_changed', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=256, verbose_name='Site address')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact email')),
                ('submitted_by_author', models.BooleanField(default=False)),
                ('is_cc', models.BooleanField(default=False, verbose_name='Licensed under creative commons')),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Nominations',
                'verbose_name': 'Nomination',
                'ordering': ('created',),
            },
        ),
    ]
