# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-20 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0007_nomination'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
    ]
