# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-20 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0008_nomination_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='contact_email',
            field=models.EmailField(max_length=254, verbose_name='Contact email'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='note',
            field=models.CharField(blank=True, max_length=128, verbose_name='Note'),
        ),
    ]
