# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0006_auto_20160422_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
