# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-23 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0003_auto_20170725_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='frequency',
            field=models.IntegerField(blank=True, choices=[(0, 'Once only'), (1, 'Once a year'), (2, 'Twice a year'), (4, 'Quarterly'), (6, 'Every two months'), (12, 'Every month'), (52, 'Weekly'), (365, 'Daily')], null=True, verbose_name='Frequency'),
        ),
    ]
