# Generated by Django 2.2.12 on 2020-08-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0004_auto_20180123_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='main_seed',
            field=models.BooleanField(default=False, verbose_name='Main seed'),
        ),
    ]
