# Generated by Django 2.2.28 on 2024-07-18 09:51

from django.db import migrations

def strip_old_seed_urls(apps, schema_editor):
    """ Strip spaces from Seed URLs with leading/trailing whitespace """
    Seed = apps.get_model("source", "Seed")
    for seed in Seed.objects.filter(url__contains=" "):
        seed.url = seed.url.strip()
        seed.save()

def reverse_strip_old_seed_urls(apps, schema_editor):
    """ I'm not adding spaces back to Seed urls... """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0006_auto_20220826_1306'),
    ]

    operations = [
        migrations.RunPython(strip_old_seed_urls,
                             reverse_code=reverse_strip_old_seed_urls),
    ]
