# Generated by Django 2.2.28 on 2024-12-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0007_strip_seed_urls_20240718_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='priority_source',
            field=models.BooleanField(default=False, verbose_name='Priority source'),
        ),
    ]
