# Generated by Django 2.2.28 on 2024-12-15 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0008_source_priority_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='publisher_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='publishers.ContactPerson', verbose_name='Publisher contact'),
        ),
    ]
