# Generated by Django 2.2.28 on 2025-08-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0009_auto_20241215_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'verbose_name': 'Keyword', 'verbose_name_plural': 'Keywords'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['name'], 'verbose_name': 'Sub category', 'verbose_name_plural': 'Sub categories'},
        ),
    ]
