# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0014_auto_20160205_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedexport',
            name='frequency',
            field=models.IntegerField(choices=[(0, 'Once only'), (1, 'Once a year'), (2, 'Twice a year'), (4, 'Quarterly'), (6, 'Every two months'), (52, 'Weekly'), (12, 'Every month'), (365, 'Daily')], verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='source',
            name='frequency',
            field=models.IntegerField(blank=True, choices=[(0, 'Once only'), (1, 'Once a year'), (2, 'Twice a year'), (4, 'Quarterly'), (6, 'Every two months'), (52, 'Weekly'), (12, 'Every month'), (365, 'Daily')], null=True, verbose_name='Frequency'),
        ),
    ]
