# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0015_auto_20160205_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seed',
            name='screenshot',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='screenshot_date',
        ),
    ]
