# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0016_auto_20160316_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='budget',
            field=models.IntegerField(blank=True, choices=[(15000, 15000), (60000, 60000), (5600, 5600)], null=True),
        ),
        migrations.AddField(
            model_name='seed',
            name='calendars',
            field=models.BooleanField(default=False, verbose_name='Calendars'),
        ),
        migrations.AddField(
            model_name='seed',
            name='gentle_fetch',
            field=models.CharField(blank=True, choices=[(b'default', 'default'), (b'low', 'low'), (b'very_low', 'very_low')], max_length=10),
        ),
        migrations.AddField(
            model_name='seed',
            name='global_reject',
            field=models.BooleanField(default=False, verbose_name='Global reject'),
        ),
        migrations.AddField(
            model_name='seed',
            name='javascript',
            field=models.BooleanField(default=False, verbose_name='Javascript'),
        ),
        migrations.AddField(
            model_name='seed',
            name='local_traps',
            field=models.BooleanField(default=False, verbose_name='Local traps'),
        ),
        migrations.AddField(
            model_name='seed',
            name='youtube',
            field=models.BooleanField(default=False, verbose_name='Youtube'),
        ),
    ]
