# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0017_auto_20160316_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=b'screenshots', verbose_name='Screenshot'),
        ),
        migrations.AddField(
            model_name='source',
            name='screenshot_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
