# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0018_auto_20160316_2321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeedExport',
        ),
    ]
