# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 10:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0019_delete_seedexport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='seed',
            name='gentle_fetch',
            field=models.CharField(blank=True, choices=[('default', 'default'), ('low', 'low'), ('very_low', 'very_low')], max_length=10),
        ),
        migrations.AlterField(
            model_name='seed',
            name='state',
            field=models.CharField(choices=[('inc', 'Include in harvest'), ('exc', 'Exclude from harvest'), ('old', 'Seed is no longer published')], default='inc', max_length=15),
        ),
        migrations.AlterField(
            model_name='source',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='source',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots', verbose_name='Screenshot'),
        ),
        migrations.AlterField(
            model_name='source',
            name='state',
            field=models.CharField(choices=[('voting', 'Voting'), ('duplicity', 'Duplicated record'), ('waiting', 'Waiting for response'), ('reevaluation', 'Waiting for reevaluation'), ('technical', 'Technical review'), ('communication', 'In communication'), ('vote_accepted', 'Accepted by staff'), ('vote_declined', 'Declined by staff'), ('success', 'Archiving accepted'), ('forced', 'Archiving without publisher consent'), ('declined', 'Declined by publisher'), ('ignored', 'Publisher ignored requests'), ('expired', 'Contract expired'), ('terminated', 'Contract terminated')], default='voting', max_length=15, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='source',
            name='suggested_by',
            field=models.CharField(blank=True, choices=[('publisher', 'Publisher'), ('visitor', 'Visitor'), ('issn', 'ISSN'), ('curator', 'Curator')], default='curator', max_length=10, null=True, verbose_name='Suggested by'),
        ),
    ]
