# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0020_auto_20160422_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['name'], 'permissions': (('manage_sources', 'Manage others sources'),), 'verbose_name': 'Source', 'verbose_name_plural': 'Sources'},
        ),
    ]
