# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0021_auto_20160504_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='source',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
