# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0022_auto_20160518_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='keywords',
            field=models.ManyToManyField(blank=True, null=True, to='source.KeyWord'),
        ),
    ]
