# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0024_auto_20170205_0137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='keyword',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
