# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0025_auto_20170212_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='source.KeyWord'),
        ),
    ]
