# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-25 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0027_source_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='dead_source',
            field=models.BooleanField(default=False, verbose_name='Source is dead'),
        ),
    ]
