# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-25 16:49
from __future__ import unicode_literals

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_changed', models.DateTimeField(auto_now=True)),
                ('vote', models.CharField(choices=[('approve', 'Include source'), ('decline', 'Exclude source'), ('wait', 'Postpone decision'), ('technical', 'Technically impossible')], max_length=10, verbose_name='Vote')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_changed',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VotingRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_changed', models.DateTimeField(auto_now=True)),
                ('date_resolved', models.DateTimeField(blank=True, null=True)),
                ('postponed_until', core.models.DatePickerField(blank=True, null=True)),
                ('state', models.CharField(choices=[('initial', 'Vote in progress'), ('approve', 'Include source'), ('decline', 'Exclude source'), ('wait', 'Postpone decision'), ('technical', 'Technically impossible')], default='initial', max_length=10, verbose_name='State')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='source.Source')),
            ],
            options={
                'verbose_name_plural': 'Elections',
                'verbose_name': 'Election',
            },
        ),
        migrations.AddField(
            model_name='vote',
            name='voting_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='voting.VotingRound', verbose_name='Round'),
        ),
    ]
