# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 00:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20151207_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voting_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='voting.VotingRound', verbose_name='Round'),
        ),
        migrations.AlterField(
            model_name='votinground',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='source.Source'),
        ),
    ]
