# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 10:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20160205_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.CharField(choices=[('approve', 'Include source'), ('decline', 'Exclude source'), ('wait', 'Postpone decision'), ('technical', 'Technically impossible')], max_length=10, verbose_name='Vote'),
        ),
        migrations.AlterField(
            model_name='votinground',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='votinground',
            name='state',
            field=models.CharField(choices=[('initial', 'Vote in progress'), ('approve', 'Include source'), ('decline', 'Exclude source'), ('wait', 'Postpone decision'), ('technical', 'Technically impossible')], default='initial', max_length=10, verbose_name='State'),
        ),
    ]
