# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blacklist_type', models.IntegerField(choices=[(0, 'Haritrex blacklist'), (1, 'Visibility blacklist')])),
                ('url_list', models.TextField(verbose_name='List of urls to block')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Blacklist',
                'verbose_name_plural': 'Blacklists',
            },
        ),
    ]
