# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-25 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('blacklist_type', models.IntegerField(choices=[(0, 'Haritrex blacklist'), (1, 'Wayback blacklist')])),
                ('url_list', models.TextField(verbose_name='List of urls to block')),
            ],
            options={
                'verbose_name_plural': 'Blacklists',
                'ordering': ('id',),
                'verbose_name': 'Blacklist',
            },
        ),
    ]
