# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='title',
            field=models.CharField(default='blacklist', max_length=256, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
