# Generated by Django 2.2 on 2019-07-03 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blacklists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='last_changed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
