# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-18 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklists', '0002_blacklist_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='blacklist_type',
            field=models.IntegerField(choices=[(0, 'Haritrex blacklist'), (1, 'Wayback blacklist')]),
        ),
    ]
