# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-25 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conspectus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150, unique=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'conspectus',
            },
        ),
        migrations.CreateModel(
            name='ConspectusSubcategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_id', models.CharField(blank=True, max_length=40, null=True)),
                ('subcategory', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'conspectus_subcategories',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=45, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.IntegerField()),
                ('active', models.IntegerField(blank=True, null=True)),
                ('date_signed', models.DateField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('addendum', models.IntegerField(blank=True, null=True)),
                ('cc', models.NullBooleanField()),
                ('blanco_contract', models.IntegerField(blank=True, null=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=150, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'contracts',
            },
        ),
        migrations.CreateModel(
            name='Curators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('vocative', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('icq', models.IntegerField(blank=True, null=True)),
                ('skype', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.IntegerField()),
                ('active_from', models.DateField(blank=True, null=True)),
                ('active_to', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('logins', models.IntegerField()),
                ('last_login', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'curators',
            },
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'keywords',
            },
        ),
        migrations.CreateModel(
            name='KeywordsResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'keywords_resources',
            },
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'publishers',
            },
        ),
        migrations.CreateModel(
            name='QaChecks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_checked', models.DateTimeField()),
                ('date_crawled', models.DateField(blank=True, null=True)),
                ('result', models.SmallIntegerField(blank=True, null=True)),
                ('solution', models.SmallIntegerField(blank=True, null=True)),
                ('solution_date', models.DateField(blank=True, null=True)),
                ('solution_user', models.IntegerField(blank=True, null=True)),
                ('proxy_problems', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('ticket_no', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'qa_checks',
            },
        ),
        migrations.CreateModel(
            name='QaChecksQaProblems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'qa_checks_qa_problems',
            },
        ),
        migrations.CreateModel(
            name='QaProblems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'qa_problems',
            },
        ),
        migrations.CreateModel(
            name='RatingRounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('rating_result', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField()),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'rating_rounds',
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField()),
                ('tech_problems', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ratings',
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_id', models.IntegerField(blank=True, null=True)),
                ('crawl_freq_id', models.IntegerField(blank=True, null=True)),
                ('resource_status_id', models.IntegerField(blank=True, null=True)),
                ('suggested_by_id', models.IntegerField(blank=True, null=True)),
                ('rating_result', models.SmallIntegerField(blank=True, null=True)),
                ('rating_last_round', models.IntegerField()),
                ('important', models.IntegerField(blank=True, null=True)),
                ('reevaluate_date', models.DateField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('aleph_id', models.CharField(blank=True, max_length=100, null=True)),
                ('issn', models.CharField(blank=True, max_length=20, null=True)),
                ('catalogued', models.DateTimeField(blank=True, null=True)),
                ('creative_commons', models.IntegerField(blank=True, null=True)),
                ('tech_problems', models.TextField(blank=True, null=True)),
                ('annotation', models.TextField(blank=True, null=True)),
                ('screenshot_date', models.DateField(blank=True, max_length=10, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'resources',
            },
        ),
        migrations.CreateModel(
            name='Seeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('seed_status_id', models.IntegerField(blank=True, null=True)),
                ('redirect', models.NullBooleanField()),
                ('robots', models.NullBooleanField()),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'seeds',
            },
        ),
        migrations.CreateModel(
            name='Subcontracts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_signed', models.DateTimeField()),
                ('blanco', models.IntegerField(blank=True, null=True)),
                ('addendum', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'subcontracts',
            },
        ),
        migrations.CreateModel(
            name='TransferRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_created=True, auto_now=True)),
                ('original_id', models.PositiveIntegerField()),
                ('target_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('original_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfer', to='contenttypes.ContentType')),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType')),
            ],
        ),
    ]
