# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_created=True, auto_now=True)),
                ('original_id', models.PositiveIntegerField()),
                ('target_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('original_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer', to='contenttypes.ContentType')),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
