# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-25 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConspectusEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150, unique=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'conspectus_en',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConspectusSubcategoriesEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_id', models.CharField(blank=True, max_length=40, null=True)),
                ('subcategory', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'conspectus_subcategories_en',
                'managed': False,
            },
        ),
    ]
