# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conspectus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150, unique=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'conspectus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConspectusSubcategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_id', models.CharField(blank=True, max_length=40, null=True)),
                ('subcategory', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'conspectus_subcategories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=45, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.IntegerField()),
                ('active', models.IntegerField(blank=True, null=True)),
                ('date_signed', models.DateField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('addendum', models.IntegerField(blank=True, null=True)),
                ('cc', models.NullBooleanField()),
                ('blanco_contract', models.IntegerField(blank=True, null=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=150, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contracts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('vocative', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('icq', models.IntegerField(blank=True, null=True)),
                ('skype', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.IntegerField()),
                ('active_from', models.DateField(blank=True, null=True)),
                ('active_to', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('logins', models.IntegerField()),
                ('last_login', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'curators',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'publishers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RatingRounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('rating_result', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField()),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rating_rounds',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField()),
                ('tech_problems', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ratings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_id', models.IntegerField(blank=True, null=True)),
                ('crawl_freq_id', models.IntegerField(blank=True, null=True)),
                ('resource_status_id', models.IntegerField(blank=True, null=True)),
                ('suggested_by_id', models.IntegerField(blank=True, null=True)),
                ('rating_result', models.SmallIntegerField(blank=True, null=True)),
                ('rating_last_round', models.IntegerField()),
                ('important', models.IntegerField(blank=True, null=True)),
                ('reevaluate_date', models.DateField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('aleph_id', models.CharField(blank=True, max_length=100, null=True)),
                ('issn', models.CharField(blank=True, max_length=20, null=True)),
                ('catalogued', models.DateTimeField(blank=True, null=True)),
                ('creative_commons', models.IntegerField(blank=True, null=True)),
                ('tech_problems', models.TextField(blank=True, null=True)),
                ('annotation', models.TextField(blank=True, null=True)),
                ('screenshot_date', models.CharField(blank=True, max_length=10, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('seed_status_id', models.IntegerField(blank=True, null=True)),
                ('redirect', models.NullBooleanField()),
                ('robots', models.NullBooleanField()),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'seeds',
                'managed': False,
            },
        ),
    ]
