# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_db', '0002_conspectus_conspectussubcategories_contacts_contracts_curators_publishers_ratingrounds_ratings_resou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrecord',
            name='original_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfer', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='transferrecord',
            name='target_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType'),
        ),
    ]
