# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_db', '0003_auto_20160205_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='QaChecks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_checked', models.DateTimeField()),
                ('date_crawled', models.DateField(blank=True, null=True)),
                ('result', models.SmallIntegerField(blank=True, null=True)),
                ('solution', models.SmallIntegerField(blank=True, null=True)),
                ('solution_date', models.DateField(blank=True, null=True)),
                ('solution_user', models.IntegerField(blank=True, null=True)),
                ('proxy_problems', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('ticket_no', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'qa_checks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QaChecksQaProblems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'qa_checks_qa_problems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QaProblems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'qa_problems',
                'managed': False,
            },
        ),
    ]
