# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_db', '0004_qachecks_qachecksqaproblems_qaproblems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcontracts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_signed', models.DateTimeField()),
                ('blanco', models.IntegerField(blank=True, null=True)),
                ('addendum', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subcontracts',
                'managed': False,
            },
        ),
    ]
