# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-18 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_blob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blob',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
