# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-25 16:48
from __future__ import unicode_literals

import ckeditor.fields
import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publishers', '__first__'),
        ('source', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_changed', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('NEGOTIATION', 'Contract in negotiation'), ('DECLINED', 'Publisher declined'), ('VALID', 'Contract is valid'), ('EXPIRED', 'Contract expired')], default='NEGOTIATION', max_length=15, verbose_name='State')),
                ('creative_commons', models.BooleanField(default=False, verbose_name='Creative commons or other OS licence')),
                ('creative_commons_type', models.CharField(blank=True, max_length=128, null=True, verbose_name='Creative commons type')),
                ('valid_from', core.models.DatePickerField(blank=True, null=True, verbose_name='Valid from')),
                ('valid_to', core.models.DatePickerField(blank=True, null=True, verbose_name='Valid to')),
                ('year', models.PositiveIntegerField(default=2017, verbose_name='Year')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='Contract file')),
                ('contract_number', models.IntegerField(blank=True, null=True, verbose_name='Contract number')),
                ('in_communication', models.BooleanField(default=False, help_text='Does the publisher responds to the emails?', verbose_name='In communication')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('parent_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_contracts', to='contracts.Contract')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publishers.Publisher')),
                ('sources', models.ManyToManyField(to='source.Source')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='EmailNegotiation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=64)),
                ('to_email', models.EmailField(max_length=254)),
                ('scheduled_date', core.models.DatePickerField(verbose_name='When to send this message')),
                ('content', ckeditor.fields.RichTextField()),
                ('template', models.CharField(max_length=64)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contracts.Contract')),
            ],
            options={
                'ordering': ('scheduled_date',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together=set([('contract_number', 'year')]),
        ),
    ]
