# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-23 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='year',
            field=models.PositiveIntegerField(default=2018, verbose_name='Year'),
        ),
    ]
