# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-02-07 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20180123_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='year',
            field=models.PositiveIntegerField(default=2019, verbose_name='Year'),
        ),
    ]
