# Generated by Django 2.2 on 2020-04-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20190207_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='year',
            field=models.PositiveIntegerField(default=2020, verbose_name='Year'),
        ),
    ]
