# Generated by Django 2.2.12 on 2020-06-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_auto_20200422_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='creative_commons',
        ),
    ]
