# Generated by Django 2.2.28 on 2024-07-04 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_auto_20201207_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='parent_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_contracts', to='contracts.Contract', verbose_name='Parent'),
        ),
    ]
