# Generated by Django 2.2.28 on 2025-08-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_auto_20240704_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='state',
            field=models.CharField(choices=[('NEGOTIATION', 'Contract in negotiation'), ('DECLINED', 'Contract terminated'), ('VALID', 'Contract is valid'), ('EXPIRED', 'Contract expired')], default='NEGOTIATION', max_length=15, verbose_name='State'),
        ),
    ]
