# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 10:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_auto_20160223_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='Contract file'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.IntegerField(blank=True, null=True, unique_for_year='created', verbose_name='Contract number'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='state',
            field=models.CharField(choices=[('NEGOTIATION', 'Contract in negotiation'), ('DECLINED', 'Publisher declined'), ('VALID', 'Contract is valid'), ('EXPIRED', 'Contract expired')], default='NEGOTIATION', max_length=15, verbose_name='State'),
        ),
    ]
