# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_contract_parent_contract'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={},
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Contract number'),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together=set([('contract_number', 'year')]),
        ),
    ]
