# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_auto_20160504_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnegotiation',
            name='to_email',
            field=models.EmailField(default='nope@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
