# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 15:07
from __future__ import unicode_literals

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0016_auto_20160504_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnegotiation',
            name='scheduled_date',
            field=core.models.DatePickerField(verbose_name='When to send this message'),
        ),
    ]
