# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_auto_20160519_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['created']},
        ),
    ]
