# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0018_auto_20160604_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-created']},
        ),
    ]
