# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0019_auto_20160714_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='year',
            field=models.PositiveIntegerField(default=2017, verbose_name='Year'),
        ),
    ]
