---
- name: "Prepare configuration template"
  hosts: all
  tasks:

    - name: "Prepare Seeder compose file."
      template:
        src: docker-compose.yaml
        dest: docker-compose-{{ env }}.yml
