---
- name: "Prepare configuration template"
  hosts: all
  tasks:
    - name: "Prepare seeder operation directory"
      file:
        dest: /home/ansible/seeder
        state: directory

    - name: "Prepare configuration for static web."
      template:
        src: nginx.conf
        dest: /home/ansible/seeder/static-nginx.conf

    - name: "Prepare Seeder compose file."
      template:
        src: docker-compose.yaml
        dest: /home/ansible/seeder/docker-compose-{{ env }}.yml

    - name: "Deployment scripts"
      template:
        src: "{{ item }}"
        dest: /home/ansible/seeder/
        mode: u+x
      loop:
        - run.sh
        - dump-screenshots.sh
        - update_vyvoj.sh