# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-23 14:02
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0002_auto_20180123_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='target_frequency',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Once only'), (1, 'Once a year'), (2, 'Twice a year'), (4, 'Quarterly'), (6, 'Every two months'), (12, 'Every month'), (52, 'Weekly'), (365, 'Daily')], max_length=19, null=True, verbose_name='Seeds by frequency'),
        ),
        migrations.AlterField(
            model_name='topiccollection',
            name='target_frequency',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Once only'), (1, 'Once a year'), (2, 'Twice a year'), (4, 'Quarterly'), (6, 'Every two months'), (12, 'Every month'), (52, 'Weekly'), (365, 'Daily')], max_length=19, null=True, verbose_name='Seeds by frequency'),
        ),
    ]
