# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0003_harvest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvest',
            name='harvest_type',
        ),
        migrations.AlterField(
            model_name='harvest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Succeeded'), (2, 'Cancelled'), (3, 'Failed')], verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='target_frequency',
            field=models.IntegerField(blank=True, choices=[(0, 'Once only'), (1, 'Once a year'), (2, 'Twice a year'), (4, 'Quarterly'), (6, 'Six times per year'), (52, 'Weekly'), (12, 'Every month'), (365, 'Daily')], null=True, verbose_name='Seeds by frequency'),
        ),
    ]
