# Generated by Django 2.2 on 2019-05-25 17:43

from django.db import migrations
import harvests.models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0003_auto_20180123_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='target_frequency',
            field=harvests.models.PatchedMultiSelectField(blank=True, choices=[(0, 'Once only'), (1, 'Once a year'), (2, 'Twice a year'), (4, 'Quarterly'), (6, 'Every two months'), (12, 'Every month'), (52, 'Weekly'), (365, 'Daily')], max_length=19, null=True, verbose_name='Seeds by frequency'),
        ),
        migrations.AlterField(
            model_name='topiccollection',
            name='target_frequency',
            field=harvests.models.PatchedMultiSelectField(blank=True, choices=[(0, 'Once only'), (1, 'Once a year'), (2, 'Twice a year'), (4, 'Quarterly'), (6, 'Every two months'), (12, 'Every month'), (52, 'Weekly'), (365, 'Daily')], max_length=19, null=True, verbose_name='Seeds by frequency'),
        ),
    ]
