# Generated by Django 2.2 on 2019-05-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0004_auto_20190525_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='archive_it',
            field=models.BooleanField(default=False),
        ),
    ]
