# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0004_auto_20160201_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
