# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0005_harvest_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='auto_created',
            field=models.BooleanField(default=False),
        ),
    ]
