# Generated by Django 2.2 on 2019-05-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0005_harvest_archive_it'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='archive_it',
            field=models.BooleanField(default=False, verbose_name='ArchiveIt'),
        ),
    ]
