# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0006_harvest_auto_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Succeeded'), (2, 'Cancelled'), (3, 'Failed')], default=0, verbose_name='State'),
        ),
    ]
