# Generated by Django 2.2 on 2019-05-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0006_auto_20190526_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='tests',
            field=models.BooleanField(default=False, verbose_name='Tests'),
        ),
    ]
