# Generated by Django 2.2 on 2019-05-28 09:18

from django.db import migrations
import harvests.models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0007_harvest_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='topic_collection_frequency',
            field=harvests.models.PatchedMultiSelectField(blank=True, choices=[(0, 'Once only'), (1, 'Once a year'), (2, 'Twice a year'), (4, 'Quarterly'), (6, 'Every two months'), (12, 'Every month'), (52, 'Weekly'), (365, 'Daily')], max_length=19, null=True, verbose_name='Topic collections by frequency'),
        ),
    ]
