# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0008_auto_20160205_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Planned'), (1, 'Running'), (2, 'Success'), (3, 'Success with failures'), (4, 'Cancelled'), (5, 'Failed')], default=0, verbose_name='State'),
        ),
    ]
