# Generated by Django 2.2 on 2019-06-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0009_topiccollection_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topiccollection',
            options={'verbose_name': 'Topic collection', 'verbose_name_plural': 'Topic collections'},
        ),
    ]
