# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0009_auto_20160208_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='seeds_frozen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
