# Generated by Django 2.2 on 2019-06-07 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0010_auto_20190607_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topiccollection',
            options={'ordering': ('order',), 'verbose_name': 'Topic collection', 'verbose_name_plural': 'Topic collections'},
        ),
    ]
