# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0011_auto_20160422_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
