# Generated by Django 2.2.12 on 2020-05-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0011_auto_20190607_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccollection',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
