# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 15:07
from __future__ import unicode_literals

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0012_auto_20160518_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='scheduled_on',
            field=core.models.DatePickerField(verbose_name='Date of harvest'),
        ),
    ]
