# Generated by Django 2.2.12 on 2020-08-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0012_auto_20200507_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='crawl_status',
            field=models.CharField(max_length=100, null=True, verbose_name='Last know crawl state'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='crawler',
            field=models.CharField(choices=[('10.10.0.200:7778', 'Crawler00'), ('10.10.0.201:7778', 'Crawler01'), ('10.10.0.202:7778', 'Crawler02'), ('10.10.0.203:7778', 'Crawler03')], default='10.10.0.200:7778', max_length=100, null=True, verbose_name='Crawler hostname + port'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='job',
            field=models.CharField(choices=[('Automated-crawl-test', 'Automated crawl test')], default='Automated-crawl-test', max_length=200, null=True, verbose_name='Job type'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='uri_budget',
            field=models.IntegerField(default=15000, verbose_name='URI Budget per domain'),
        ),
    ]
