# Generated by Django 2.2.12 on 2020-11-03 06:30

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0012_auto_20200507_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccollection',
            name='date_to',
            field=core.models.DatePickerField(blank=True, null=True, verbose_name='Date to'),
        ),
    ]
