# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0013_auto_20160519_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='annotation',
            field=models.TextField(blank=True, null=True, verbose_name='Annotation'),
        ),
    ]
