# Generated by Django 2.2.12 on 2020-11-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0013_auto_20201103_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='seeds_not_harvested',
            field=models.TextField(blank=True, null=True, verbose_name='Seeds not harvested'),
        ),
    ]
