# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 17:43
from __future__ import unicode_literals

import ckeditor.fields
import core.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0027_source_slug'),
        ('harvests', '0014_harvest_annotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_changed', models.DateTimeField(auto_now=True)),
                ('target_frequency', models.IntegerField(blank=True, choices=[(0, 'Once only'), (1, 'Once a year'), (2, 'Twice a year'), (4, 'Quarterly'), (6, 'Every two months'), (52, 'Weekly'), (12, 'Every month'), (365, 'Daily')], null=True, verbose_name='Seeds by frequency')),
                ('custom_seeds', models.TextField(blank=True, help_text='One URL per line', null=True, verbose_name='Custom seeds URL')),
                ('status', models.IntegerField(choices=[(2, 'Running'), (1, 'New'), (3, 'Finished')], default=1, verbose_name='State')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('seeds_frozen', models.TextField(blank=True, null=True)),
                ('auto_created', models.BooleanField(default=False)),
                ('scheduled_on', core.models.DatePickerField(blank=True, null=True, verbose_name='Date of harvest')),
                ('annotation', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('custom_sources', models.ManyToManyField(blank=True, to='source.Source', verbose_name='Included sources')),
                ('keywords', models.ManyToManyField(to='source.KeyWord')),
            ],
            options={
                'verbose_name_plural': 'Topic collections',
                'ordering': ['id'],
                'verbose_name': 'Topic collection',
            },
        ),
        migrations.AlterModelOptions(
            name='harvest',
            options={},
        ),
    ]
