# Generated by Django 2.2.20 on 2021-05-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0014_harvest_seeds_not_harvested'),
    ]

    operations = [
        migrations.AddField(
            model_name='topiccollection',
            name='aggregation_with_same_type',
            field=models.BooleanField(default=True, verbose_name='Aggregation with same type'),
        ),
        migrations.AddField(
            model_name='topiccollection',
            name='collection_alias',
            field=models.CharField(blank=True, max_length=64, verbose_name='Collection alias'),
        ),
    ]
