# Generated by Django 2.2.20 on 2021-08-03 08:35

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0015_auto_20210504_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='scheduled_on',
            field=core.models.DateTimePickerField(verbose_name='Date of harvest'),
        ),
        migrations.AlterField(
            model_name='topiccollection',
            name='scheduled_on',
            field=core.models.DateTimePickerField(blank=True, null=True, verbose_name='Date of harvest'),
        ),
    ]
