# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 18:47
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0015_auto_20170224_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='topiccollection',
            name='annotation_cs',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='topiccollection',
            name='annotation_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='topiccollection',
            name='title_cs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topiccollection',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
