# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0016_auto_20170224_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccollection',
            name='annotation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='topiccollection',
            name='annotation_cs',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='topiccollection',
            name='annotation_en',
            field=models.TextField(null=True),
        ),
    ]
