# Generated by Django 2.2.20 on 2021-08-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0017_external_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Planned'), (6, 'Ready to harvest'), (1, 'Running'), (2, 'Success'), (3, 'Success with failures'), (4, 'Cancelled'), (5, 'Failed')], default=0, verbose_name='State'),
        ),
    ]
