# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 01:58
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0017_auto_20170225_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccollection',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title_cs', unique=True),
        ),
    ]
