# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0018_auto_20170225_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='topiccollection',
            name='all_open',
            field=models.BooleanField(default=False, verbose_name='All sources are under open license or contract'),
            preserve_default=False,
        ),
    ]
