# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 22:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('harvests', '0019_topiccollection_all_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='topiccollection',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Curator'),
            preserve_default=False,
        ),
    ]
