# Generated by Django 2.2.20 on 2021-12-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0020_harvest_json_frozen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='custom_seeds',
            field=models.TextField(blank=True, help_text='Sem vložte všechna semínka, po uložení zde zůstanou zdroje bez záznamu v Seederu, ostatní budu v poli Přiřazené zdroje', null=True, verbose_name='Custom seeds URL'),
        ),
        migrations.AlterField(
            model_name='topiccollection',
            name='custom_seeds',
            field=models.TextField(blank=True, help_text='Sem vložte všechna semínka, po uložení zde zůstanou zdroje bez záznamu v Seederu, ostatní budu v poli Přiřazené zdroje', null=True, verbose_name='Custom seeds URL'),
        ),
    ]
