# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0020_topiccollection_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments')),
                ('topic_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvests.TopicCollection')),
            ],
        ),
    ]
