# Generated by Django 2.2.20 on 2022-05-03 09:31

from django.db import migrations
import harvests.models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0021_auto_20211221_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccollection',
            name='target_frequency',
            field=harvests.models.PatchedMultiSelectField(blank=True, choices=[(0, 'Once only'), (1, 'Once a year'), (2, 'Twice a year'), (4, 'Quarterly'), (6, 'Every two months'), (12, 'Every month'), (52, 'Weekly'), (365, 'Daily')], max_length=19, null=True, verbose_name='Frequency'),
        ),
    ]
