# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-10 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0021_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='attachments', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='topiccollection',
            name='annotation',
            field=models.TextField(verbose_name='annotation'),
        ),
        migrations.AlterField(
            model_name='topiccollection',
            name='annotation_cs',
            field=models.TextField(null=True, verbose_name='annotation'),
        ),
        migrations.AlterField(
            model_name='topiccollection',
            name='annotation_en',
            field=models.TextField(null=True, verbose_name='annotation'),
        ),
        migrations.AlterField(
            model_name='topiccollection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='topiccollection',
            name='keywords',
            field=models.ManyToManyField(to='source.KeyWord', verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='topiccollection',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='topiccollection',
            name='title_cs',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='topiccollection',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
    ]
