# Generated by Django 2.2.20 on 2022-12-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0022_auto_20220503_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaltopiccollection',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
