# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-21 14:22
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0022_auto_20170310_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='topic_collections',
            field=models.ManyToManyField(to='harvests.TopicCollection', verbose_name='Topic collections'),
        ),
        migrations.AddField(
            model_name='topiccollection',
            name='date_from',
            field=core.models.DatePickerField(null=True, verbose_name='Date from'),
        ),
        migrations.AddField(
            model_name='topiccollection',
            name='date_to',
            field=core.models.DatePickerField(null=True, verbose_name='Date to'),
        ),
    ]
