# Generated by Django 2.2.20 on 2022-12-10 08:08

import core.models
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0023_auto_20221209_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccollection',
            name='date_from',
            field=core.models.DatePickerField(default=datetime.date.today, null=True, verbose_name='Date from'),
        ),
    ]
