# Generated by Django 2.2.28 on 2023-07-04 07:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0024_auto_20221210_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaltopiccollection',
            name='annotation',
            field=ckeditor.fields.RichTextField(verbose_name='annotation'),
        ),
        migrations.AlterField(
            model_name='externaltopiccollection',
            name='annotation_cs',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='annotation'),
        ),
        migrations.AlterField(
            model_name='externaltopiccollection',
            name='annotation_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='annotation'),
        ),
    ]
