# Generated by Django 2.2.28 on 2025-07-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0025_auto_20230704_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaltopiccollection',
            name='image_text',
            field=models.CharField(blank=True, help_text='If image text is set, it will be used to generate an SVG image for the website, otherwise image will be used.', max_length=32, verbose_name='Image text'),
        ),
    ]
