''' Key is upper letter, value is upper regex to match it + diacritics '''
ALPHABET_SEARCH_CONVERSION = {
    '#': r'[^a-zA-Z]',
    'A': r'[AÁ]',
    'B': r'B',
    'C': r'[CČ]',
    'D': r'[DĎ]',
    'E': r'[EÉĚ]',
    'F': r'F',
    'G': r'G',
    'H': r'H',
    'CH': r'CH',
    'I': r'[IÍ]',
    'J': r'J',
    'K': r'K',
    'L': r'L',
    'M': r'M',
    'N': r'[NŇ]',
    'O': r'[OÓ]',
    'P': r'P',
    'Q': r'Q',
    'R': r'[RŘ]',
    'S': r'[SŠ]',
    'T': r'[TŤ]',
    'U': r'[UÚŮ]',
    'V': r'V',
    'W': r'W',
    'X': r'X',
    'Y': r'[YÝ]',
    'Z': r'[ZŽ]',
}
